; ---------------------------------------------------------------------------
; - I/O Interface ROM BIOS (EQUATES.INC)                                    -
; - Integrant part of I/O Interface ROM BIOS                                -
; - Copyright (C) 1998-2020 Alexandru Groza of Microprogramming TECHNIQUES  -
; - All rights reserved.                                                    -
; ---------------------------------------------------------------------------
; - License: GNU General Public License v3.0                                -
; ---------------------------------------------------------------------------

ROMSTART           equ 00h
ROMSIZE            equ 2000h
ROMBLOCKS          equ ROMSIZE / 512